#!/bin/bash

rowSize=0
colSize=0
while read row
do
	count=0
	for i in $row
	do
		((count++))
	done

	#set column size using first row, verify other rows are same 	
	if [ "$rowSize" -eq 0 ]
	then
		echo "first row"
		colSize="$count"
	else
		if [ "$count" -ne "$colSize" ]
		then
			echo "ERROR -- matrix not complete"
		fi
	fi

	((rowSize++))
done < $1

echo -e "Number of rows:$rowSize"
echo -e "Number of columns:$colSize"
